### PR TITLE
GHCJS implementation

### PR DESCRIPTION
**Pull request by nomeata**
This compiles and seems to work:

```
measureAll()
Running JavaScript... 5 main.js:28:25
JavaScript: min: 1ms max: 2ms avg: 1.25ms main.js:42:17
Running ghcjs... 5 main.js:28:25
ghcjs: min: 187ms max: 209ms avg: 191.77ms
```

I am not sure how idiomatic that is, and if I may be doing something really stupid performance wise.

Also I had to jump through quite a few hoops to get a mutable UInt8Array type, and to expose from Haskell a function that returns a value.

You need `ghcjs` somehow. `nix-shell -p haskell.compilers.ghcjs` is one way to get it. Then `cabal build --ghcjs` works.

I did not fully automate the setup, hence leaving this in Draft state.

Also see <https://www.reddit.com/r/haskell/comments/vpnh53/comment/ieoktf0/?utm_source=reddit&utm_medium=web2x&context=3>

### CODE REVIEW

**Comment by gergoerdi** [comment]
I'd love to try this out, but I know absolutely nothing about nix... What is missing from my system here?

```
$ nix-shell -p haskell.compilers.ghcjs
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:13
```

**Comment by nomeata** [comment]
How did you install `nix`? Maybe the installation configured your environment to set `NIX_PATH`, but you need to re-login for that to take effect?

In any case, this should work:
```
nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/09c32b0bda4db98d6454e910206188e85d5b04cc.tar.gz -p haskell.compiler.ghcjs
```

(This is not the most principled way of setting up an environment like this, but one of the fastest one.)

Hmm, it looks like ghcjs is not actually provided by the Nix cache, so this will not only download a bunch of stuff, but also build a bunch of stuff for a while … once you see it doing something, maybe just let it sit there over lunch or so :)

When you come back you should be in a shell with `ghcjs` installed.

**Comment by gergoerdi** [comment]
> How did you install `nix`?

I don't remember doing anything special other than installing it from an Ubuntu `.deb`.

**Comment by gergoerdi** [comment]
This got marked as 'merged' by accident, and now I don't know how to reopen it...

**Pull request merged**
